/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consolidacion;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class LIDERES extends javax.swing.JPanel {
private Connection connection=null;
private ResultSet rs= null;
private Statement s=null;
  /**
   * Creates new form LIDER
   */
  public LIDERES() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    nombre = new javax.swing.JTextField();
    jToggleButton1 = new javax.swing.JToggleButton();
    jLabel4 = new javax.swing.JLabel();
    apellidos = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    direccion = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    barrio = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    dia = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    mes = new javax.swing.JTextField();
    año = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    correo = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    grupo = new javax.swing.JComboBox<>();
    cedula = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    celular = new javax.swing.JTextField();
    jLabel32 = new javax.swing.JLabel();
    asignado = new javax.swing.JTextField();
    jButton4 = new javax.swing.JButton();
    estado = new javax.swing.JComboBox<>();
    jPanel2 = new javax.swing.JPanel();
    jLabel14 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    mcedula = new javax.swing.JTextField();
    mnombre = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    mapellidos = new javax.swing.JTextField();
    mestado_civil = new javax.swing.JTextField();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    mbarrio = new javax.swing.JComboBox<>();
    mdia = new javax.swing.JTextField();
    jLabel20 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    mmes = new javax.swing.JTextField();
    jLabel22 = new javax.swing.JLabel();
    maño = new javax.swing.JTextField();
    jLabel23 = new javax.swing.JLabel();
    jLabel24 = new javax.swing.JLabel();
    jLabel25 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();
    jLabel27 = new javax.swing.JLabel();
    mgrupo = new javax.swing.JComboBox<>();
    mcorreo = new javax.swing.JTextField();
    mcelular = new javax.swing.JTextField();
    mdireccion = new javax.swing.JTextField();
    jLabel28 = new javax.swing.JLabel();
    jLabel33 = new javax.swing.JLabel();
    masignado = new javax.swing.JTextField();
    jToggleButton2 = new javax.swing.JToggleButton();
    jButton2 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel29 = new javax.swing.JLabel();
    jLabel30 = new javax.swing.JLabel();
    ecedula = new javax.swing.JTextField();
    jLabel31 = new javax.swing.JLabel();
    enombre = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();

    jToggleButton1.setText("CREAR");
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton1ActionPerformed(evt);
      }
    });

    jLabel4.setText("APELLIDOS ");

    jLabel5.setText("ESTADO CIVIL");

    jLabel6.setText("DIRECCION");

    direccion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        direccionActionPerformed(evt);
      }
    });

    jLabel7.setText("BARRIO");

    barrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "elija el barrio", "MONTOYA", "LUIS CARLOS", "CENTRO\t", "VILLAS DE GRANADA \t", "VILLA OLIMPICA\t", "ESTERO\t", "VILLAMONICA\t", "PARAISO", " " }));
    barrio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        barrioActionPerformed(evt);
      }
    });

    jLabel8.setText("FECHA DE NACIMIENTO");

    jLabel9.setText("DIA");

    jLabel10.setText("MES");

    mes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mesActionPerformed(evt);
      }
    });

    año.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        añoActionPerformed(evt);
      }
    });

    jLabel11.setText("AÑO");

    jLabel12.setText("CORREO ELECTRONICO");

    jLabel1.setText("CREAR LIDER");

    jLabel13.setText("ASISTE GRUPO?");

    jLabel2.setText("CEDULA");

    grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    cedula.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cedulaActionPerformed(evt);
      }
    });

    jLabel15.setText("CELULAR");

    jLabel3.setText("NOMBRES ");

    jLabel32.setText("ASIGNADO A:");

    jButton4.setText("MENU");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                      .addGap(55, 55, 55))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(jLabel13)
                  .addComponent(jLabel15)
                  .addComponent(jLabel32)))
              .addComponent(jButton4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(barrio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cedula)
              .addComponent(nombre)
              .addComponent(apellidos)
              .addComponent(grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(celular)
              .addComponent(correo)
              .addComponent(asignado)
              .addComponent(direccion, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(498, 498, 498)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(488, 488, 488)
            .addComponent(jToggleButton1)))
        .addContainerGap(349, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(jLabel1)
        .addGap(38, 38, 38)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(26, 26, 26)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addGap(24, 24, 24)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(9, 9, 9)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9)
          .addComponent(jLabel10)
          .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel11)
          .addComponent(jLabel8))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel12))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel13))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel15))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel32)
              .addComponent(asignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4)
            .addGap(20, 20, 20)))
        .addComponent(jToggleButton1)
        .addGap(41, 41, 41))
    );

    jTabbedPane1.addTab("CREAR LIDER", jPanel1);

    jLabel14.setText("CEDULA");

    jLabel16.setText("MODIFICAR LIDER");

    mcedula.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mcedulaActionPerformed(evt);
      }
    });

    jLabel17.setText("APELLIDOS ");

    jLabel18.setText("ESTADO CIVIL");

    jLabel19.setText("DIRECCION");

    mbarrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "elija el barrio", "MONTOYA", "LUIS CARLOS", "CENTRO\t", "VILLAS DE GRANADA \t", "VILLA OLIMPICA\t", "ESTERO\t", "VILLAMONICA\t", "PARAISO", " " }));
    mbarrio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mbarrioActionPerformed(evt);
      }
    });

    jLabel20.setText("MES");

    jLabel21.setText("DIA");

    mmes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mmesActionPerformed(evt);
      }
    });

    jLabel22.setText("AÑO");

    maño.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mañoActionPerformed(evt);
      }
    });

    jLabel23.setText("FECHA DE NACIMIENTO");

    jLabel24.setText("BARRIO");

    jLabel25.setText("CORREO ELECTRONICO");

    jLabel26.setText("ASISTE GRUPO?");

    jLabel27.setText("CELULAR");

    mgrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    mdireccion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mdireccionActionPerformed(evt);
      }
    });

    jLabel28.setText("NOMBRE");

    jLabel33.setText("ASIGNADO A:");

    jToggleButton2.setText("MODIFICAR");

    jButton2.setText("BUSCAR");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(359, 359, 359)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel28)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(masignado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(49, 49, 49)
            .addComponent(jButton2)
            .addGap(234, 234, 234))))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(519, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(456, 456, 456))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addComponent(jToggleButton2)
            .addGap(504, 504, 504))))
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(356, 356, 356)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel23)
                  .addComponent(jLabel24)
                  .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel18)
                  .addComponent(jLabel17))
                .addGap(55, 55, 55))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel26)
                .addComponent(jLabel27))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jLabel21)
              .addGap(18, 18, 18)
              .addComponent(mdia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(jLabel20)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(mmes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
              .addComponent(jLabel22)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(maño, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(mbarrio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mdireccion)
            .addComponent(mnombre)
            .addComponent(mapellidos)
            .addComponent(mestado_civil)
            .addComponent(mgrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mcelular)
            .addComponent(mcorreo))
          .addContainerGap(357, Short.MAX_VALUE)))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(73, 73, 73)
        .addComponent(jLabel16)
        .addGap(41, 41, 41)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel14)
          .addComponent(jButton2))
        .addGap(23, 23, 23)
        .addComponent(jLabel28)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel33)
          .addComponent(masignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jToggleButton2)
        .addGap(14, 14, 14))
      .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
          .addGap(179, 179, 179)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(jLabel17)
              .addGap(18, 18, 18)
              .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(mestado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel18)))
            .addGroup(jPanel2Layout.createSequentialGroup()
              .addComponent(mnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(24, 24, 24)
              .addComponent(mapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(32, 32, 32)))
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(mdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel19))
          .addGap(18, 18, 18)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(mbarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel24))
          .addGap(18, 18, 18)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(mdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel21)
            .addComponent(jLabel20)
            .addComponent(mmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(maño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel22)
            .addComponent(jLabel23))
          .addGap(18, 18, 18)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(mcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel25))
          .addGap(18, 18, 18)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(mgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel26))
          .addGap(18, 18, 18)
          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(mcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel27))
          .addContainerGap(96, Short.MAX_VALUE)))
    );

    jTabbedPane1.addTab("MODIFICAR LIDER", jPanel2);

    jLabel29.setText("ELIMINAR LIDER ");

    jLabel30.setText("CEDULA");

    ecedula.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ecedulaActionPerformed(evt);
      }
    });

    jLabel31.setText("NOMBRE");

    enombre.setEditable(false);
    enombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        enombreActionPerformed(evt);
      }
    });

    jButton1.setText("ELIMINAR");

    jButton3.setText("BUSCAR");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(385, 385, 385)
            .addComponent(jLabel29))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(266, 266, 266)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel30)
              .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(139, 139, 139)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(ecedula)
              .addComponent(enombre, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
            .addGap(43, 43, 43)
            .addComponent(jButton3))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(401, 401, 401)
            .addComponent(jButton1)))
        .addContainerGap(364, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addComponent(jLabel29)
        .addGap(48, 48, 48)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel30)
          .addComponent(ecedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton3))
        .addGap(28, 28, 28)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel31)
          .addComponent(enombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(38, 38, 38)
        .addComponent(jButton1)
        .addContainerGap(344, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("ELIMINAR LIDER", jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(103, 103, 103)
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(132, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(18, Short.MAX_VALUE))
    );

    jTabbedPane1.getAccessibleContext().setAccessibleName("CREAR LIDER");
  }// </editor-fold>//GEN-END:initComponents
public void conexion()
{
    if(connection !=null){
		return;
	}
	
	String url ="jdbc:postgresql://localhost:5433/CONSOLIDACION";
	String password ="ideafix";
	try{
	   Class.forName("org.postgresql.Driver");
	   
	   connection=DriverManager.getConnection(url,"postgres",password);
	   
	   if(connection!=null){
		   System.out.println("Conectando a Base de Datos...");
	   }
	} catch (Exception e){
		System.out.println("Problemas de Conexion");
	}

}
  private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cedulaActionPerformed

  private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_direccionActionPerformed

  private void barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_barrioActionPerformed

  private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mesActionPerformed

  private void añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_añoActionPerformed

  private void mcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcedulaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mcedulaActionPerformed

  private void mbarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarrioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mbarrioActionPerformed

  private void mmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmesActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mmesActionPerformed

  private void mañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mañoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mañoActionPerformed

  private void mdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdireccionActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_mdireccionActionPerformed

  private void ecedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecedulaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ecedulaActionPerformed

  private void enombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enombreActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_enombreActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
setLayout(new BorderLayout());

	removeAll();
        updateUI();
        repaint();
        MENU menu = new MENU();
        add(menu, BorderLayout.CENTER);
        //pack();
 
	
	setVisible(true);
	setSize(1000,1000);      // TODO add your handling code here:
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
conexion();
  String c = cedula.getText();
  String n = nombre.getText();
  String a = apellidos.getText();
  Object est = estado.getSelectedItem(); 
  String es = String.valueOf(est);
  String di = direccion.getText();
  Object ba = barrio.getSelectedItem(); 
  String b = String.valueOf(ba); 
  String d = dia.getText();
  String m = mes.getText();
  String añ = año.getText();
  String co = correo.getText();
  Object gru = barrio.getSelectedItem(); 
  String gr = String.valueOf(gru);
  String  ce = celular.getText();
	try{
     s=connection.createStatement();
    int z=s.executeUpdate("INSERT INTO lider  Values('"+c+"','"+n+"','"+a+"','"+es+"','"+di+"','"+b+"','"+añ+"-"+m+"-"+d+"','"+co+"','"+gr+"','"+ce+"')");
	 if(z==1){
	   System.out.println("Se agrego el registro de manera exitosa");
	  }else{
	   System.out.println("Ocurrio un problema al agregar el registro");
	  }
    }catch (Exception e){
		System.out.println("Error de conexion");
	}
// TODO add your handling code here:
  }//GEN-LAST:event_jToggleButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField apellidos;
  private javax.swing.JTextField asignado;
  private javax.swing.JTextField año;
  private javax.swing.JComboBox<String> barrio;
  private javax.swing.JTextField cedula;
  private javax.swing.JTextField celular;
  private javax.swing.JTextField correo;
  private javax.swing.JTextField dia;
  private javax.swing.JTextField direccion;
  private javax.swing.JTextField ecedula;
  private javax.swing.JTextField enombre;
  private javax.swing.JComboBox<String> estado;
  private javax.swing.JComboBox<String> grupo;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel25;
  private javax.swing.JLabel jLabel26;
  private javax.swing.JLabel jLabel27;
  private javax.swing.JLabel jLabel28;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel31;
  private javax.swing.JLabel jLabel32;
  private javax.swing.JLabel jLabel33;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToggleButton jToggleButton2;
  private javax.swing.JTextField mapellidos;
  private javax.swing.JTextField masignado;
  private javax.swing.JTextField maño;
  private javax.swing.JComboBox<String> mbarrio;
  private javax.swing.JTextField mcedula;
  private javax.swing.JTextField mcelular;
  private javax.swing.JTextField mcorreo;
  private javax.swing.JTextField mdia;
  private javax.swing.JTextField mdireccion;
  private javax.swing.JTextField mes;
  private javax.swing.JTextField mestado_civil;
  private javax.swing.JComboBox<String> mgrupo;
  private javax.swing.JTextField mmes;
  private javax.swing.JTextField mnombre;
  private javax.swing.JTextField nombre;
  // End of variables declaration//GEN-END:variables
}
