/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consolidacion;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Container;

/**
 *
 * @author USUARIO
 */
public class MENU extends javax.swing.JPanel {

  /**
   * Creates new form MENU
   */
  public MENU() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();

    jButton1.setText("NUEVO");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("LIDER");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton3.setBackground(new java.awt.Color(0, 51, 255));
    jButton3.setText("AUX. SUPERVISOR");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setText("SUPERVISOR");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(145, 145, 145)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton4)
          .addComponent(jButton3)
          .addComponent(jButton2)
          .addComponent(jButton1))
        .addContainerGap(416, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(121, 121, 121)
        .addComponent(jButton1)
        .addGap(41, 41, 41)
        .addComponent(jButton2)
        .addGap(30, 30, 30)
        .addComponent(jButton3)
        .addGap(26, 26, 26)
        .addComponent(jButton4)
        .addContainerGap(189, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setLayout(new BorderLayout());
	
	

	removeAll();
        updateUI();
        repaint();
        NUEVO nuevo = new NUEVO();
        add(nuevo, BorderLayout.CENTER);
        //pack();
 
	
	setVisible(true);
	setSize(1000,1000);
	//setDefaultCloseOperation(EXIT_ON_CLOSE);
	    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	setLayout(new BorderLayout());

	removeAll();
        updateUI();
        repaint();
        LIDERES lider = new LIDERES();
        add(lider, BorderLayout.CENTER);
        //pack();
 
	
	setVisible(true);
	setSize(1000,1000);    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   setLayout(new BorderLayout());

	removeAll();
        updateUI();
        repaint();
        AUXSUPER auxsuper = new AUXSUPER();
        add(auxsuper, BorderLayout.CENTER);
        //pack();
 
	
	setVisible(true);
	setSize(1000,1000);  // TODO add your handling code here:
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   setLayout(new BorderLayout());

	removeAll();
        updateUI();
        repaint();
        SUPERVISOR supervisor = new SUPERVISOR();
        add(supervisor, BorderLayout.CENTER);
        //pack();
 
	
	setVisible(true);
	setSize(1000,1000); // TODO add your handling code here:
  }//GEN-LAST:event_jButton4ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  // End of variables declaration//GEN-END:variables
}
